import { AppRole, Permission } from "@/types/auth";

export const ROLE_PERMISSIONS: Record<AppRole, Permission[]> = {
  ADMIN: [
    "dashboard.view",
    "vehicles.read", "vehicles.create", "vehicles.update", "vehicles.delete",
    "drivers.read", "drivers.create", "drivers.update", "drivers.suspend",
    "trips.read", "trips.create", "trips.assign", "trips.update", "trips.cancel",
    "dispatch.view", "dispatch.manage",
    "maintenance.read", "maintenance.create", "maintenance.update", "maintenance.approve",
    "fuel.read", "fuel.create", "fuel.update",
    "expenses.read", "expenses.create", "expenses.approve", "expenses.reject",
    "compliance.read", "compliance.manage",
    "analytics.view", "reports.export",
    "users.read", "users.invite", "users.update", "users.delete",
    "roles.read", "roles.manage",
    "audit.read",
    "organization.read", "organization.update",
    "settings.read", "settings.update",
  ],
  FLEET_MANAGER: [
    "dashboard.view",
    "vehicles.read", "vehicles.create", "vehicles.update",
    "drivers.read", "drivers.create", "drivers.update",
    "trips.read", "trips.create", "trips.assign", "trips.update",
    "dispatch.view", "dispatch.manage",
    "maintenance.read", "maintenance.create", "maintenance.update", "maintenance.approve",
    "fuel.read", "fuel.create",
    "expenses.read", "expenses.create",
    "compliance.read", "compliance.manage",
    "analytics.view", "reports.export",
    "users.read",
  ],
  DISPATCHER: [
    "dashboard.view",
    "vehicles.read",
    "drivers.read",
    "trips.read", "trips.create", "trips.assign", "trips.update",
    "dispatch.view", "dispatch.manage",
    "fuel.read",
    "compliance.read",
  ],
  DRIVER: [
    "dashboard.view",
    "trips.read",
    "fuel.read", "fuel.create",
    "expenses.read", "expenses.create",
  ],
  SAFETY_OFFICER: [
    "dashboard.view",
    "vehicles.read",
    "drivers.read", "drivers.suspend",
    "compliance.read", "compliance.manage",
    "analytics.view",
    "audit.read",
  ],
  FINANCIAL_ANALYST: [
    "dashboard.view",
    "fuel.read",
    "expenses.read", "expenses.approve", "expenses.reject",
    "analytics.view", "reports.export",
  ],
};
